USE [ALPHANEXT]
GO

/****** Object:  Table [dbo].[PRODUCTS]    Script Date: 08/17/2016 14:13:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTTYPE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PRODUCTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-------------------------------------------------------------------

alter table ALPHANEXT..WPNAMELIST add IDNEW int
update ALPHANEXT..WPNAMELIST set IDNEW = ID

--таблицы для которых надо удалить а потом добавить снова те же внешние ключи:
--remarkwp
alter table ALPHANEXT..REMARKWP drop constraint FK_REMARKWP_WPNAMELIST

--runcard
alter table ALPHANEXT..RUNCARDS drop constraint FK_RUNCARDS_WPNAMELIST
--cicuitboards 
alter table ALPHANEXT..CIRCUITBOARDS drop constraint FK_CIRCUITBOARDS_WPNAMELIST

alter table ALPHANEXT..WPNAMELIST drop constraint PK_WPNAMELIST
alter table ALPHANEXT..WPNAMELIST drop column ID

EXEC sp_RENAME 'ALPHANEXT..WPNAMELIST.IDNEW' , 'ID', 'COLUMN'

alter table ALPHANEXT..WPNAMELIST alter column ID int not null
alter table ALPHANEXT..WPNAMELIST add primary key (ID)

---------------------------кабели-----------------------------------------
alter table ALPHANEXT..CABLELIST add IDNEW int
update ALPHANEXT..CABLELIST set IDNEW = ID + 1000
update ALPHANEXT..SUMMON set IDWP = IDWP+1000 where WPTYPE = 'CABLELIST'
alter table ALPHANEXT..CABLES drop constraint FK_CABLES_CABLELIST
alter table ALPHANEXT..CABLELIST drop constraint PK_CABLELIST
alter table ALPHANEXT..CABLELIST drop column ID
update ALPHANEXT..CABLES set IDCABLE = IDCABLE+1000

EXEC sp_RENAME 'ALPHANEXT..CABLELIST.IDNEW' , 'ID', 'COLUMN'

alter table ALPHANEXT..CABLELIST alter column ID int not null
alter table ALPHANEXT..CABLELIST add primary key (ID)
ALTER TABLE ALPHANEXT..CABLES ADD CONSTRAINT FK_CABLELIST FOREIGN KEY (IDCABLE) REFERENCES ALPHANEXT..CABLELIST(ID)


-----------------------------жгуты-------------------------------------------
alter table ALPHANEXT..ZHGUTLIST add IDNEW int
update ALPHANEXT..ZHGUTLIST set IDNEW = ID + 2000
update ALPHANEXT..SUMMON set IDWP = IDWP+2000 where WPTYPE = 'ZHGUTLIST'
alter table ALPHANEXT..ZHGUTS drop constraint FK_ZHGUTS_ZHGUTLIST
alter table ALPHANEXT..ZHGUTLIST drop constraint PK_ZHGUTLIST
alter table ALPHANEXT..ZHGUTLIST drop column ID
update ALPHANEXT..ZHGUTS set IDZHGUT = IDZHGUT+2000

EXEC sp_RENAME 'ALPHANEXT..ZHGUTLIST.IDNEW' , 'ID', 'COLUMN'

alter table ALPHANEXT..ZHGUTLIST alter column ID int not null
alter table ALPHANEXT..ZHGUTLIST add primary key (ID)
ALTER TABLE ALPHANEXT..ZHGUTS ADD CONSTRAINT FK_ZHGUTLIST FOREIGN KEY (IDZHGUT)
 REFERENCES ALPHANEXT..ZHGUTLIST(ID) on delete cascade

--------------вставляем продукты в PRODUCTS----
set identity_insert ALPHANEXT..PRODUCTS on
go
insert into ALPHANEXT..PRODUCTS (ID,PRODUCTTYPE)
select ID,'WPNAMELIST' from ALPHANEXT..WPNAMELIST

insert into ALPHANEXT..PRODUCTS (ID,PRODUCTTYPE)
select ID,'CABLELIST' from ALPHANEXT..CABLELIST

insert into ALPHANEXT..PRODUCTS (ID,PRODUCTTYPE)
select ID,'ZHGUTLIST' from ALPHANEXT..ZHGUTLIST

set identity_insert ALPHANEXT..PRODUCTS off
--------------------------------------------------
--добавить внештние ключи в !!!!
--remarkwp
ALTER TABLE ALPHANEXT..REMARKWP ADD CONSTRAINT FK_REMARKWP_PRODUCTS FOREIGN KEY (IDWP)
 REFERENCES ALPHANEXT..PRODUCTS(ID) on delete cascade

--runcard
ALTER TABLE ALPHANEXT..RUNCARDS ADD CONSTRAINT FK_RUNCARDS_PRODUCTS FOREIGN KEY (IDWP)
 REFERENCES ALPHANEXT..PRODUCTS(ID) on delete cascade

--cicuitboards
ALTER TABLE ALPHANEXT..CIRCUITBOARDS ADD CONSTRAINT FK_CIRCUITBOARDS_PRODUCTS FOREIGN KEY (IDWP)
 REFERENCES ALPHANEXT..PRODUCTS(ID) on delete cascade
-------------------------------------------------------------------
--добавляем FK на жгуты кабеля в комплекты кабелей и жгутов

--нужно вставить в продукты ID
ALTER TABLE ALPHANEXT..CABLES ADD CONSTRAINT FK_PRODUCT_CABLE FOREIGN KEY (IDWP)
 REFERENCES ALPHANEXT..PRODUCTS(ID) on delete cascade

--нужно вставить в продукты ID
ALTER TABLE ALPHANEXT..ZHGUTS ADD CONSTRAINT FK_PRODUCT_ZHGUT FOREIGN KEY (IDWP)
 REFERENCES ALPHANEXT..PRODUCTS(ID) on delete cascade


----------------------------------------------------------------------
--добавляем FK на summon
ALTER TABLE ALPHANEXT..SUMMON add CONSTRAINT FK_SUMMON_PRODUCT FOREIGN KEY (IDWP)
 REFERENCES ALPHANEXT..PRODUCTS(ID)
------------------------------------------------------------
--FK на категории и подкатегории


----для кабелей
ALTER TABLE ALPHANEXT..CABLELIST 
add CONSTRAINT FK_CABLELIST_CATEGORY FOREIGN KEY (IDCATEGORY) REFERENCES ALPHANEXT..CATEGORYLIST(ID)

insert into ALPHANEXT..SUBCATEGORYLIST (IDCATEGORY,SUBCATNAME) values (12,'ВСЕ')
insert into ALPHANEXT..SUBCATEGORYLIST (IDCATEGORY,SUBCATNAME) values (12,'НЕ ПРИСВОЕНО')
--здесь остановиться и посмотреть какие ID были присвоены подкатегориям
--и вообще почему для кабелей не было подкатегорий все и не присвоено?????????
update ALPHANEXT..CABLELIST set IDSUBCAT =  where IDSUBCAT is null or IDSUBCAT = 0 or IDSUBCAT = 1000
ALTER TABLE ALPHANEXT..CABLELIST 
add CONSTRAINT FK_CABLELIST_SUBCATEGORY FOREIGN KEY (IDSUBCAT) REFERENCES ALPHANEXT..SUBCATEGORYLIST(ID)
------для жгутов
ALTER TABLE ALPHANEXT..ZHGUTLIST 
add CONSTRAINT FK_ZHGUTLIST_CATEGORY FOREIGN KEY (IDCATEGORY) REFERENCES ALPHANEXT..CATEGORYLIST(ID)
ALTER TABLE ALPHANEXT..ZHGUTLIST 
add CONSTRAINT FK_ZHGUTLIST_SUBCATEGORY FOREIGN KEY (IDSUBCAT) REFERENCES ALPHANEXT..SUBCATEGORYLIST(ID)
-----для изделий
ALTER TABLE ALPHANEXT..WPNAMELIST 
add CONSTRAINT FK_WPNAMELIST_CATEGORY FOREIGN KEY (IDCATEGORY) REFERENCES ALPHANEXT..CATEGORYLIST(ID)
insert into ALPHANEXT..SUBCATEGORYLIST (IDCATEGORY,SUBCATNAME) values (2,'НЕ ПРИСВОЕНО')
--здесь остановиться и посмотреть какой ID присвоился и выполнить следующую команду с этим ID
update ALPHANEXT..WPNAMELIST set IDSUBCAT = 102 where IDSUBCAT is null or IDSUBCAT = 0
--потом проверить норма или нет работает после писвоения...
ALTER TABLE ALPHANEXT..WPNAMELIST 
add CONSTRAINT FK_WPNAMELIST_SUBCATEGORY FOREIGN KEY (IDSUBCAT) REFERENCES ALPHANEXT..SUBCATEGORYLIST(ID)
------------------------------------------------------------

--выбрать каких извещений нет, чтоб удалить битые покупные материалы
select * from ALPHANEXT..PURCHASEDMATERIALS A where NOT exists (select 1 from ALPHANEXT..SUMMON B where A.IDS = B.ID)
delete from ALPHANEXT..PURCHASEDMATERIALS where ID = 
ALTER TABLE ALPHANEXT..PURCHASEDMATERIALS 
add CONSTRAINT FK_PURCHASEDMATERIALS_SUMMON FOREIGN KEY (IDS) 
REFERENCES ALPHANEXT..SUMMON(ID) on delete cascade
--------------------
ALTER TABLE ALPHANEXT..PREFERENCES 
add CONSTRAINT FK_PREFERENCES_USER FOREIGN KEY (IDUSER) 
REFERENCES ALPHANEXT..USERS(ID) on delete cascade
------------------------------------
update ALPHANEXT..SUMMON set IDPACKING = 1 where IDPACKING is null
alter table ALPHANEXT..SUMMON alter column IDPACKING int not null
alter table ALPHANEXT..SUMMON add constraint DF_IDPACKING default(1) for IDPACKING
ALTER TABLE ALPHANEXT..SUMMON 
add CONSTRAINT FK_SUMMON_PACKINGLIST FOREIGN KEY (IDPACKING) REFERENCES ALPHANEXT..PACKINGLIST(ID)
---------------
ALTER TABLE ALPHANEXT..SUMMON 
add CONSTRAINT FK_SUMMON_STATUSLIST FOREIGN KEY (IDSTATUS) REFERENCES ALPHANEXT..STATUSLIST(ID)
---------------------------------
alter table ALPHANEXT..SUMMON alter column IDSUBST int not null
set identity_insert ALPHANEXT..STATUSLIST on
go
insert into ALPHANEXT..STATUSLIST (ID,SNAME) values (0,'НЕ ПРИСВОЕНО')
set identity_insert ALPHANEXT..STATUSLIST off
ALTER TABLE ALPHANEXT..SUMMON 
add CONSTRAINT FK_SUMMON_SUBSTATUSLIST FOREIGN KEY (IDSUBST) REFERENCES ALPHANEXT..STATUSLIST(ID)
---------------------------------
ALTER TABLE ALPHANEXT..USERS 
add CONSTRAINT FK_USERS_ROLES FOREIGN KEY ([ROLE]) REFERENCES ALPHANEXT..ROLES(ID)
---------------------------------
delete from ALPHANEXT..SUMMONVIEWS where ID in
(
select ID from ALPHANEXT..SUMMONVIEWS A where NOT exists (select 1 from ALPHANEXT..SUMMON B where A.IDSUMMON = B.ID)
)
ALTER TABLE ALPHANEXT..SUMMONVIEWS 
add CONSTRAINT FK_SUMMONVIEWS_SUMMON FOREIGN KEY (IDSUMMON) 
REFERENCES ALPHANEXT..SUMMON(ID) on delete cascade
ALTER TABLE ALPHANEXT..SUMMONVIEWS 
add CONSTRAINT FK_SUMMONVIEWS_USER FOREIGN KEY (IDUSER) 
REFERENCES ALPHANEXT..USERS(ID) on delete cascade
--------------------------------------
update ALPHANEXT..SUMMON set IDCUSTOMER = 0 where IDCUSTOMER is null
set identity_insert ALPHANEXT..CUSTOMERS on
insert into ALPHANEXT..CUSTOMERS (ID,CNAME,ADDRESS,CONTACT,CONTACTEXE,CONTACTFINLOG)
values (0,'<нет>','<нет>','<нет>','<нет>','<нет>')
set identity_insert ALPHANEXT..CUSTOMERS off
alter table ALPHANEXT..SUMMON alter column IDCUSTOMER int not null
alter table ALPHANEXT..SUMMON add constraint DF_IDCUSTOMER default(0) for IDCUSTOMER
ALTER TABLE ALPHANEXT..SUMMON 
add CONSTRAINT FK_SUMMON_CUTOMERS FOREIGN KEY (IDCUSTOMER) REFERENCES ALPHANEXT..CUSTOMERS(ID)
-----------------------------------------------------
ALTER TABLE ALPHANEXT..CUSTOMERDEPTLIST 
add CONSTRAINT FK_CUSTOMERDEPTLIST_CUSTOMERS FOREIGN KEY (IDCUSTOMER) 
REFERENCES ALPHANEXT..CUSTOMERS(ID) on delete cascade
--------------------------------------------------
set identity_insert ALPHANEXT..CUSTOMERDEPTLIST on
insert into ALPHANEXT..CUSTOMERDEPTLIST (ID,IDCUSTOMER,DEPTNAME,CONTACTEXE,CONTACTFINLOG)
values (0,0,'<нет>','<нет>','<нет>')
set identity_insert ALPHANEXT..CUSTOMERDEPTLIST off
update ALPHANEXT..SUMMON set IDCUSTOMERDEPT=0 where IDCUSTOMERDEPT is null
alter table ALPHANEXT..SUMMON alter column IDCUSTOMERDEPT int not null
alter table ALPHANEXT..SUMMON add constraint DF_IDCUSTOMERDEPT default(0) for IDCUSTOMERDEPT

ALTER TABLE ALPHANEXT..SUMMON 
add CONSTRAINT FK_SUMMON_CUSTOMERDEPTLIST FOREIGN KEY (IDCUSTOMERDEPT) REFERENCES ALPHANEXT..CUSTOMERDEPTLIST(ID)
----------------------------------------------------
--курстатус пока отложить. тут надо IDS переделать
--ALTER TABLE ALPHANEXT..CURSTATUS 
--add CONSTRAINT FK_CURSTATUS_SUMMON FOREIGN KEY (IDS) REFERENCES ALPHANEXT..SUMMON(IDS)
------------------------------------------------------
insert into ALPHANEXT..NOTIFICATIONTYPE (NTYPE) values ('оповещения для OTK')
insert into ALPHANEXT..NOTIFICATIONTYPE (NTYPE) values ('оповещения для конструктора')
insert into ALPHANEXT..NOTIFICATIONTYPE (NTYPE) values ('оповещения для ПДБ')
insert into ALPHANEXT..NOTIFICATIONTYPE (NTYPE) values ('оповещения для Бухгалтера')
ALTER TABLE ALPHANEXT..NOTIFICATIONS 
add CONSTRAINT FK_NOTIFICATIONS_NOTIFICATIONTYPE FOREIGN KEY (IDNTYPE) REFERENCES ALPHANEXT..NOTIFICATIONTYPE(ID)
ALTER TABLE ALPHANEXT..NOTIFICATIONS 
add CONSTRAINT FK_NOTIFICATIONS_SUMMON FOREIGN KEY (IDSUMMON) 
REFERENCES ALPHANEXT..SUMMON(ID) on delete cascade
--------------
delete from ALPHANEXT..NOTES where ID in 
(
select ID from ALPHANEXT..NOTES A where NOT exists (select 1 from ALPHANEXT..SUMMON B where A.IDSUMMON = B.ID)
)
ALTER TABLE ALPHANEXT..NOTES 
add CONSTRAINT FK_NOTES_SUMMON FOREIGN KEY (IDSUMMON)
 REFERENCES ALPHANEXT..SUMMON(ID) on delete cascade
------------------------
ALTER TABLE ALPHANEXT..WPNAMELIST 
drop CONSTRAINT FK_WPNAMELIST_PRODUCTS
ALTER TABLE ALPHANEXT..WPNAMELIST 
add CONSTRAINT FK_WPNAMELIST_PRODUCTS FOREIGN KEY (ID) 
REFERENCES ALPHANEXT..PRODUCTS(ID) on delete cascade

ALTER TABLE ALPHANEXT..CABLELIST 
drop CONSTRAINT FK_CABLELIST_PRODUCTS  
ALTER TABLE ALPHANEXT..CABLELIST 
add CONSTRAINT FK_CABLELIST_PRODUCTS FOREIGN KEY (ID) 
REFERENCES ALPHANEXT..PRODUCTS(ID) on delete cascade

ALTER TABLE ALPHANEXT..ZHGUTLIST 
add CONSTRAINT FK_ZHGUTLIST_PRODUCTS FOREIGN KEY (ID) 
REFERENCES ALPHANEXT..PRODUCTS(ID) on delete cascade

----------------------
НАПИСАТЬ СКРИПТ, КОТОРЫЙ УДАЛИТ ПОДКАТЕГОРИИ, КОТОРЫЕ ПРИНАДЛЕЖАТ КАТЕГОРИИ "ВСЕ" ИЛИ "НЕ ПРИСВОЕНО"
-------------------------
alter table ALPHANEXT..SUMMON drop column ACCEPTANCE
alter table ALPHANEXT..SUMMON drop column IDCURSTATUS
drop table ALPHANEXT..MOUNTINGKITLIST
-------------------------
update ALPHANEXT..SUMMON set IDACCEPT = 1 where IDACCEPT is null
alter table ALPHANEXT..SUMMON alter column IDACCEPT int not null
alter table ALPHANEXT..SUMMON add constraint DF_IDACCEPT default(1) for IDACCEPT
ALTER TABLE ALPHANEXT..SUMMON 
add CONSTRAINT FK_SUMMON_ACCEPTLIST FOREIGN KEY (IDACCEPT) 
REFERENCES ALPHANEXT..ACCEPTLIST(ID)
----------------------------
ALTER TABLE ALPHANEXT..NOTES 
add CONSTRAINT FK_NOTES_USERS FOREIGN KEY (IDUSER) 
REFERENCES ALPHANEXT..USERS(ID)
-----------------------------
alter table ALPHANEXT..CURSTATUS add IDSUMMON int

update  A
set A.IDSUMMON = B.ID
from ALPHANEXT..CURSTATUS A
inner join ALPHANEXT..SUMMON B on A.IDS = B.IDS

delete from ALPHANEXT..CURSTATUS where IDSUMMON is null
alter table ALPHANEXT..CURSTATUS alter column IDSUMMON int not null

ALTER TABLE ALPHANEXT..CURSTATUS 
add CONSTRAINT FK_CURSTATUS_SUMMON FOREIGN KEY (IDSUMMON) 
REFERENCES ALPHANEXT..SUMMON(ID) on delete cascade

ALTER TABLE ALPHANEXT..CURSTATUS 
add CONSTRAINT FK_CURSTATUS_STATUSLIST FOREIGN KEY (STATID) 
REFERENCES ALPHANEXT..STATUSLIST(ID) 

-------------------------------
alter table ALPHANEXT..CURSUBSTATUS add IDSUMMON int

update  A
set A.IDSUMMON = B.ID
from ALPHANEXT..CURSUBSTATUS A
inner join ALPHANEXT..SUMMON B on A.IDS = B.IDS

delete from ALPHANEXT..CURSUBSTATUS where IDSUMMON is null
alter table ALPHANEXT..CURSUBSTATUS alter column IDSUMMON int not null

ALTER TABLE ALPHANEXT..CURSUBSTATUS 
add CONSTRAINT FK_CURSUBSTATUS_SUMMON FOREIGN KEY (IDSUMMON) 
REFERENCES ALPHANEXT..SUMMON(ID) on delete cascade

ALTER TABLE ALPHANEXT..CURSUBSTATUS 
add CONSTRAINT FK_CURSUBSTATUS_STATUSLIST FOREIGN KEY (STATID) 
REFERENCES ALPHANEXT..STATUSLIST(ID) 

---------------------------
alter table ALPHANEXT..CURSTATUS drop column IDS
alter table ALPHANEXT..CURSUBSTATUS drop column IDS
---------------------------
--ALTER TABLE ALPHANEXT..SUBCATEGORYLIST 
--drop CONSTRAINT FK_SUBCATEGORYLIST_CATEGORYLIST

ALTER TABLE ALPHANEXT..SUBCATEGORYLIST 
add CONSTRAINT FK_SUBCATEGORYLIST_CATEGORYLIST FOREIGN KEY (IDCATEGORY) 
REFERENCES ALPHANEXT..CATEGORYLIST(ID)  on delete cascade

