//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 19.07.2012 17:12:35
namespace SummonManager
{
    
    /// <summary>
    /// There are no comments for PRDCEntities in the schema.
    /// </summary>
    public partial class PRDCEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new PRDCEntities object using the connection string found in the 'PRDCEntities' section of the application configuration file.
        /// </summary>
        public PRDCEntities() : 
                base("name=PRDCEntities", "PRDCEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PRDCEntities object.
        /// </summary>
        public PRDCEntities(string connectionString) : 
                base(connectionString, "PRDCEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PRDCEntities object.
        /// </summary>
        public PRDCEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "PRDCEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for CURSTATUS in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CURSTATUS> CURSTATUS
        {
            get
            {
                if ((this._CURSTATUS == null))
                {
                    this._CURSTATUS = base.CreateQuery<CURSTATUS>("[CURSTATUS]");
                }
                return this._CURSTATUS;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CURSTATUS> _CURSTATUS;
        /// <summary>
        /// There are no comments for CUSTOMERS in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CUSTOMERS> CUSTOMERS
        {
            get
            {
                if ((this._CUSTOMERS == null))
                {
                    this._CUSTOMERS = base.CreateQuery<CUSTOMERS>("[CUSTOMERS]");
                }
                return this._CUSTOMERS;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CUSTOMERS> _CUSTOMERS;
        /// <summary>
        /// There are no comments for HISTORY in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<HISTORY> HISTORY
        {
            get
            {
                if ((this._HISTORY == null))
                {
                    this._HISTORY = base.CreateQuery<HISTORY>("[HISTORY]");
                }
                return this._HISTORY;
            }
        }
        private global::System.Data.Objects.ObjectQuery<HISTORY> _HISTORY;
        /// <summary>
        /// There are no comments for PAYSTATUS in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PAYSTATUS> PAYSTATUS
        {
            get
            {
                if ((this._PAYSTATUS == null))
                {
                    this._PAYSTATUS = base.CreateQuery<PAYSTATUS>("[PAYSTATUS]");
                }
                return this._PAYSTATUS;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PAYSTATUS> _PAYSTATUS;
        /// <summary>
        /// There are no comments for ROLES in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ROLES> ROLES
        {
            get
            {
                if ((this._ROLES == null))
                {
                    this._ROLES = base.CreateQuery<ROLES>("[ROLES]");
                }
                return this._ROLES;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ROLES> _ROLES;
        /// <summary>
        /// There are no comments for STATUSLIST in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<STATUSLIST> STATUSLIST
        {
            get
            {
                if ((this._STATUSLIST == null))
                {
                    this._STATUSLIST = base.CreateQuery<STATUSLIST>("[STATUSLIST]");
                }
                return this._STATUSLIST;
            }
        }
        private global::System.Data.Objects.ObjectQuery<STATUSLIST> _STATUSLIST;
        /// <summary>
        /// There are no comments for SUMMON in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SUMMON> SUMMON
        {
            get
            {
                if ((this._SUMMON == null))
                {
                    this._SUMMON = base.CreateQuery<SUMMON>("[SUMMON]");
                }
                return this._SUMMON;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SUMMON> _SUMMON;
        /// <summary>
        /// There are no comments for USERS in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<USERS> USERS
        {
            get
            {
                if ((this._USERS == null))
                {
                    this._USERS = base.CreateQuery<USERS>("[USERS]");
                }
                return this._USERS;
            }
        }
        private global::System.Data.Objects.ObjectQuery<USERS> _USERS;
        /// <summary>
        /// There are no comments for CURSTATUS in the schema.
        /// </summary>
        public void AddToCURSTATUS(CURSTATUS cURSTATUS)
        {
            base.AddObject("CURSTATUS", cURSTATUS);
        }
        /// <summary>
        /// There are no comments for CUSTOMERS in the schema.
        /// </summary>
        public void AddToCUSTOMERS(CUSTOMERS cUSTOMERS)
        {
            base.AddObject("CUSTOMERS", cUSTOMERS);
        }
        /// <summary>
        /// There are no comments for HISTORY in the schema.
        /// </summary>
        public void AddToHISTORY(HISTORY hISTORY)
        {
            base.AddObject("HISTORY", hISTORY);
        }
        /// <summary>
        /// There are no comments for PAYSTATUS in the schema.
        /// </summary>
        public void AddToPAYSTATUS(PAYSTATUS pAYSTATUS)
        {
            base.AddObject("PAYSTATUS", pAYSTATUS);
        }
        /// <summary>
        /// There are no comments for ROLES in the schema.
        /// </summary>
        public void AddToROLES(ROLES rOLES)
        {
            base.AddObject("ROLES", rOLES);
        }
        /// <summary>
        /// There are no comments for STATUSLIST in the schema.
        /// </summary>
        public void AddToSTATUSLIST(STATUSLIST sTATUSLIST)
        {
            base.AddObject("STATUSLIST", sTATUSLIST);
        }
        /// <summary>
        /// There are no comments for SUMMON in the schema.
        /// </summary>
        public void AddToSUMMON(SUMMON sUMMON)
        {
            base.AddObject("SUMMON", sUMMON);
        }
        /// <summary>
        /// There are no comments for USERS in the schema.
        /// </summary>
        public void AddToUSERS(USERS uSERS)
        {
            base.AddObject("USERS", uSERS);
        }
    }
    /// <summary>
    /// There are no comments for PRDCModel.CURSTATUS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PRDCModel", Name="CURSTATUS")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CURSTATUS : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CURSTATUS object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="sUMMID">Initial value of SUMMID.</param>
        /// <param name="sTATID">Initial value of STATID.</param>
        /// <param name="cAUSE">Initial value of CAUSE.</param>
        /// <param name="cHANGEDATE">Initial value of CHANGEDATE.</param>
        public static CURSTATUS CreateCURSTATUS(int id, int sUMMID, string sTATID, string cAUSE, global::System.DateTime cHANGEDATE)
        {
            CURSTATUS cURSTATUS = new CURSTATUS();
            cURSTATUS.ID = id;
            cURSTATUS.SUMMID = sUMMID;
            cURSTATUS.STATID = sTATID;
            cURSTATUS.CAUSE = cAUSE;
            cURSTATUS.CHANGEDATE = cHANGEDATE;
            return cURSTATUS;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SUMMID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SUMMID
        {
            get
            {
                return this._SUMMID;
            }
            set
            {
                this.OnSUMMIDChanging(value);
                this.ReportPropertyChanging("SUMMID");
                this._SUMMID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SUMMID");
                this.OnSUMMIDChanged();
            }
        }
        private int _SUMMID;
        partial void OnSUMMIDChanging(int value);
        partial void OnSUMMIDChanged();
        /// <summary>
        /// There are no comments for Property STATID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string STATID
        {
            get
            {
                return this._STATID;
            }
            set
            {
                this.OnSTATIDChanging(value);
                this.ReportPropertyChanging("STATID");
                this._STATID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("STATID");
                this.OnSTATIDChanged();
            }
        }
        private string _STATID;
        partial void OnSTATIDChanging(string value);
        partial void OnSTATIDChanged();
        /// <summary>
        /// There are no comments for Property CAUSE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CAUSE
        {
            get
            {
                return this._CAUSE;
            }
            set
            {
                this.OnCAUSEChanging(value);
                this.ReportPropertyChanging("CAUSE");
                this._CAUSE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CAUSE");
                this.OnCAUSEChanged();
            }
        }
        private string _CAUSE;
        partial void OnCAUSEChanging(string value);
        partial void OnCAUSEChanged();
        /// <summary>
        /// There are no comments for Property CHANGEDATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CHANGEDATE
        {
            get
            {
                return this._CHANGEDATE;
            }
            set
            {
                this.OnCHANGEDATEChanging(value);
                this.ReportPropertyChanging("CHANGEDATE");
                this._CHANGEDATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CHANGEDATE");
                this.OnCHANGEDATEChanged();
            }
        }
        private global::System.DateTime _CHANGEDATE;
        partial void OnCHANGEDATEChanging(global::System.DateTime value);
        partial void OnCHANGEDATEChanged();
    }
    /// <summary>
    /// There are no comments for PRDCModel.CUSTOMERS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PRDCModel", Name="CUSTOMERS")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CUSTOMERS : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CUSTOMERS object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="cNAME">Initial value of CNAME.</param>
        /// <param name="cONTACT">Initial value of CONTACT.</param>
        public static CUSTOMERS CreateCUSTOMERS(int id, string cNAME, string cONTACT)
        {
            CUSTOMERS cUSTOMERS = new CUSTOMERS();
            cUSTOMERS.ID = id;
            cUSTOMERS.CNAME = cNAME;
            cUSTOMERS.CONTACT = cONTACT;
            return cUSTOMERS;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property CNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CNAME
        {
            get
            {
                return this._CNAME;
            }
            set
            {
                this.OnCNAMEChanging(value);
                this.ReportPropertyChanging("CNAME");
                this._CNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CNAME");
                this.OnCNAMEChanged();
            }
        }
        private string _CNAME;
        partial void OnCNAMEChanging(string value);
        partial void OnCNAMEChanged();
        /// <summary>
        /// There are no comments for Property CONTACT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTACT
        {
            get
            {
                return this._CONTACT;
            }
            set
            {
                this.OnCONTACTChanging(value);
                this.ReportPropertyChanging("CONTACT");
                this._CONTACT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CONTACT");
                this.OnCONTACTChanged();
            }
        }
        private string _CONTACT;
        partial void OnCONTACTChanging(string value);
        partial void OnCONTACTChanged();
    }
    /// <summary>
    /// There are no comments for PRDCModel.HISTORY in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PRDCModel", Name="HISTORY")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class HISTORY : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new HISTORY object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="hDATE">Initial value of HDATE.</param>
        public static HISTORY CreateHISTORY(int id, global::System.DateTime hDATE)
        {
            HISTORY hISTORY = new HISTORY();
            hISTORY.ID = id;
            hISTORY.HDATE = hDATE;
            return hISTORY;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property HDATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime HDATE
        {
            get
            {
                return this._HDATE;
            }
            set
            {
                this.OnHDATEChanging(value);
                this.ReportPropertyChanging("HDATE");
                this._HDATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HDATE");
                this.OnHDATEChanged();
            }
        }
        private global::System.DateTime _HDATE;
        partial void OnHDATEChanging(global::System.DateTime value);
        partial void OnHDATEChanged();
        /// <summary>
        /// There are no comments for Property ACTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ACTION
        {
            get
            {
                return this._ACTION;
            }
            set
            {
                this.OnACTIONChanging(value);
                this.ReportPropertyChanging("ACTION");
                this._ACTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ACTION");
                this.OnACTIONChanged();
            }
        }
        private string _ACTION;
        partial void OnACTIONChanging(string value);
        partial void OnACTIONChanged();
        /// <summary>
        /// There are no comments for Property NOTE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NOTE
        {
            get
            {
                return this._NOTE;
            }
            set
            {
                this.OnNOTEChanging(value);
                this.ReportPropertyChanging("NOTE");
                this._NOTE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NOTE");
                this.OnNOTEChanged();
            }
        }
        private string _NOTE;
        partial void OnNOTEChanging(string value);
        partial void OnNOTEChanged();
    }
    /// <summary>
    /// There are no comments for PRDCModel.PAYSTATUS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PRDCModel", Name="PAYSTATUS")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PAYSTATUS : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PAYSTATUS object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="sNAME">Initial value of SNAME.</param>
        public static PAYSTATUS CreatePAYSTATUS(int id, string sNAME)
        {
            PAYSTATUS pAYSTATUS = new PAYSTATUS();
            pAYSTATUS.ID = id;
            pAYSTATUS.SNAME = sNAME;
            return pAYSTATUS;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SNAME
        {
            get
            {
                return this._SNAME;
            }
            set
            {
                this.OnSNAMEChanging(value);
                this.ReportPropertyChanging("SNAME");
                this._SNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SNAME");
                this.OnSNAMEChanged();
            }
        }
        private string _SNAME;
        partial void OnSNAMEChanging(string value);
        partial void OnSNAMEChanged();
    }
    /// <summary>
    /// There are no comments for PRDCModel.ROLES in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PRDCModel", Name="ROLES")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ROLES : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ROLES object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="rOLENAME">Initial value of ROLENAME.</param>
        public static ROLES CreateROLES(int id, string rOLENAME)
        {
            ROLES rOLES = new ROLES();
            rOLES.ID = id;
            rOLES.ROLENAME = rOLENAME;
            return rOLES;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ROLENAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ROLENAME
        {
            get
            {
                return this._ROLENAME;
            }
            set
            {
                this.OnROLENAMEChanging(value);
                this.ReportPropertyChanging("ROLENAME");
                this._ROLENAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ROLENAME");
                this.OnROLENAMEChanged();
            }
        }
        private string _ROLENAME;
        partial void OnROLENAMEChanging(string value);
        partial void OnROLENAMEChanged();
    }
    /// <summary>
    /// There are no comments for PRDCModel.STATUSLIST in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PRDCModel", Name="STATUSLIST")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class STATUSLIST : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new STATUSLIST object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="sNAME">Initial value of SNAME.</param>
        public static STATUSLIST CreateSTATUSLIST(int id, string sNAME)
        {
            STATUSLIST sTATUSLIST = new STATUSLIST();
            sTATUSLIST.ID = id;
            sTATUSLIST.SNAME = sNAME;
            return sTATUSLIST;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property SNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SNAME
        {
            get
            {
                return this._SNAME;
            }
            set
            {
                this.OnSNAMEChanging(value);
                this.ReportPropertyChanging("SNAME");
                this._SNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SNAME");
                this.OnSNAMEChanged();
            }
        }
        private string _SNAME;
        partial void OnSNAMEChanging(string value);
        partial void OnSNAMEChanged();
    }
    /// <summary>
    /// There are no comments for PRDCModel.SUMMON in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PRDCModel", Name="SUMMON")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SUMMON : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SUMMON object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="iDS">Initial value of IDS.</param>
        /// <param name="qUANTITY">Initial value of QUANTITY.</param>
        /// <param name="iDPAYSTATUS">Initial value of IDPAYSTATUS.</param>
        public static SUMMON CreateSUMMON(int id, string iDS, int qUANTITY, int iDPAYSTATUS)
        {
            SUMMON sUMMON = new SUMMON();
            sUMMON.ID = id;
            sUMMON.IDS = iDS;
            sUMMON.QUANTITY = qUANTITY;
            sUMMON.IDPAYSTATUS = iDPAYSTATUS;
            return sUMMON;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property IDS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IDS
        {
            get
            {
                return this._IDS;
            }
            set
            {
                this.OnIDSChanging(value);
                this.ReportPropertyChanging("IDS");
                this._IDS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IDS");
                this.OnIDSChanged();
            }
        }
        private string _IDS;
        partial void OnIDSChanging(string value);
        partial void OnIDSChanged();
        /// <summary>
        /// There are no comments for Property TECHREQPATH in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TECHREQPATH
        {
            get
            {
                return this._TECHREQPATH;
            }
            set
            {
                this.OnTECHREQPATHChanging(value);
                this.ReportPropertyChanging("TECHREQPATH");
                this._TECHREQPATH = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TECHREQPATH");
                this.OnTECHREQPATHChanged();
            }
        }
        private string _TECHREQPATH;
        partial void OnTECHREQPATHChanging(string value);
        partial void OnTECHREQPATHChanged();
        /// <summary>
        /// There are no comments for Property QUANTITY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int QUANTITY
        {
            get
            {
                return this._QUANTITY;
            }
            set
            {
                this.OnQUANTITYChanging(value);
                this.ReportPropertyChanging("QUANTITY");
                this._QUANTITY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("QUANTITY");
                this.OnQUANTITYChanged();
            }
        }
        private int _QUANTITY;
        partial void OnQUANTITYChanging(int value);
        partial void OnQUANTITYChanged();
        /// <summary>
        /// There are no comments for Property PTIME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> PTIME
        {
            get
            {
                return this._PTIME;
            }
            set
            {
                this.OnPTIMEChanging(value);
                this.ReportPropertyChanging("PTIME");
                this._PTIME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PTIME");
                this.OnPTIMEChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _PTIME;
        partial void OnPTIMEChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPTIMEChanged();
        /// <summary>
        /// There are no comments for Property ACCEPTANCE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ACCEPTANCE
        {
            get
            {
                return this._ACCEPTANCE;
            }
            set
            {
                this.OnACCEPTANCEChanging(value);
                this.ReportPropertyChanging("ACCEPTANCE");
                this._ACCEPTANCE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ACCEPTANCE");
                this.OnACCEPTANCEChanged();
            }
        }
        private string _ACCEPTANCE;
        partial void OnACCEPTANCEChanging(string value);
        partial void OnACCEPTANCEChanged();
        /// <summary>
        /// There are no comments for Property IDCUSTOMER in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> IDCUSTOMER
        {
            get
            {
                return this._IDCUSTOMER;
            }
            set
            {
                this.OnIDCUSTOMERChanging(value);
                this.ReportPropertyChanging("IDCUSTOMER");
                this._IDCUSTOMER = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDCUSTOMER");
                this.OnIDCUSTOMERChanged();
            }
        }
        private global::System.Nullable<int> _IDCUSTOMER;
        partial void OnIDCUSTOMERChanging(global::System.Nullable<int> value);
        partial void OnIDCUSTOMERChanged();
        /// <summary>
        /// There are no comments for Property CONTRACT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTRACT
        {
            get
            {
                return this._CONTRACT;
            }
            set
            {
                this.OnCONTRACTChanging(value);
                this.ReportPropertyChanging("CONTRACT");
                this._CONTRACT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CONTRACT");
                this.OnCONTRACTChanged();
            }
        }
        private string _CONTRACT;
        partial void OnCONTRACTChanging(string value);
        partial void OnCONTRACTChanged();
        /// <summary>
        /// There are no comments for Property IDPAYSTATUS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPAYSTATUS
        {
            get
            {
                return this._IDPAYSTATUS;
            }
            set
            {
                this.OnIDPAYSTATUSChanging(value);
                this.ReportPropertyChanging("IDPAYSTATUS");
                this._IDPAYSTATUS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDPAYSTATUS");
                this.OnIDPAYSTATUSChanged();
            }
        }
        private int _IDPAYSTATUS;
        partial void OnIDPAYSTATUSChanging(int value);
        partial void OnIDPAYSTATUSChanged();
        /// <summary>
        /// There are no comments for Property SHIPPING in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SHIPPING
        {
            get
            {
                return this._SHIPPING;
            }
            set
            {
                this.OnSHIPPINGChanging(value);
                this.ReportPropertyChanging("SHIPPING");
                this._SHIPPING = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SHIPPING");
                this.OnSHIPPINGChanged();
            }
        }
        private string _SHIPPING;
        partial void OnSHIPPINGChanging(string value);
        partial void OnSHIPPINGChanged();
        /// <summary>
        /// There are no comments for Property DELIVERY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DELIVERY
        {
            get
            {
                return this._DELIVERY;
            }
            set
            {
                this.OnDELIVERYChanging(value);
                this.ReportPropertyChanging("DELIVERY");
                this._DELIVERY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DELIVERY");
                this.OnDELIVERYChanged();
            }
        }
        private string _DELIVERY;
        partial void OnDELIVERYChanging(string value);
        partial void OnDELIVERYChanged();
        /// <summary>
        /// There are no comments for Property SISP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> SISP
        {
            get
            {
                return this._SISP;
            }
            set
            {
                this.OnSISPChanging(value);
                this.ReportPropertyChanging("SISP");
                this._SISP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SISP");
                this.OnSISPChanged();
            }
        }
        private global::System.Nullable<bool> _SISP;
        partial void OnSISPChanging(global::System.Nullable<bool> value);
        partial void OnSISPChanged();
        /// <summary>
        /// There are no comments for Property NOTE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NOTE
        {
            get
            {
                return this._NOTE;
            }
            set
            {
                this.OnNOTEChanging(value);
                this.ReportPropertyChanging("NOTE");
                this._NOTE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NOTE");
                this.OnNOTEChanged();
            }
        }
        private string _NOTE;
        partial void OnNOTEChanging(string value);
        partial void OnNOTEChanged();
        /// <summary>
        /// There are no comments for Property IDSTATUS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> IDSTATUS
        {
            get
            {
                return this._IDSTATUS;
            }
            set
            {
                this.OnIDSTATUSChanging(value);
                this.ReportPropertyChanging("IDSTATUS");
                this._IDSTATUS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDSTATUS");
                this.OnIDSTATUSChanged();
            }
        }
        private global::System.Nullable<int> _IDSTATUS;
        partial void OnIDSTATUSChanging(global::System.Nullable<int> value);
        partial void OnIDSTATUSChanged();
    }
    /// <summary>
    /// There are no comments for PRDCModel.USERS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PRDCModel", Name="USERS")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class USERS : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new USERS object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="fIO">Initial value of FIO.</param>
        /// <param name="lOGIN">Initial value of LOGIN.</param>
        /// <param name="pASS">Initial value of PASS.</param>
        /// <param name="rOLE">Initial value of ROLE.</param>
        public static USERS CreateUSERS(int id, string fIO, string lOGIN, string pASS, int rOLE)
        {
            USERS uSERS = new USERS();
            uSERS.ID = id;
            uSERS.FIO = fIO;
            uSERS.LOGIN = lOGIN;
            uSERS.PASS = pASS;
            uSERS.ROLE = rOLE;
            return uSERS;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property FIO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FIO
        {
            get
            {
                return this._FIO;
            }
            set
            {
                this.OnFIOChanging(value);
                this.ReportPropertyChanging("FIO");
                this._FIO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FIO");
                this.OnFIOChanged();
            }
        }
        private string _FIO;
        partial void OnFIOChanging(string value);
        partial void OnFIOChanged();
        /// <summary>
        /// There are no comments for Property LOGIN in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN
        {
            get
            {
                return this._LOGIN;
            }
            set
            {
                this.OnLOGINChanging(value);
                this.ReportPropertyChanging("LOGIN");
                this._LOGIN = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LOGIN");
                this.OnLOGINChanged();
            }
        }
        private string _LOGIN;
        partial void OnLOGINChanging(string value);
        partial void OnLOGINChanged();
        /// <summary>
        /// There are no comments for Property PASS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PASS
        {
            get
            {
                return this._PASS;
            }
            set
            {
                this.OnPASSChanging(value);
                this.ReportPropertyChanging("PASS");
                this._PASS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PASS");
                this.OnPASSChanged();
            }
        }
        private string _PASS;
        partial void OnPASSChanging(string value);
        partial void OnPASSChanged();
        /// <summary>
        /// There are no comments for Property ROLE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ROLE
        {
            get
            {
                return this._ROLE;
            }
            set
            {
                this.OnROLEChanging(value);
                this.ReportPropertyChanging("ROLE");
                this._ROLE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ROLE");
                this.OnROLEChanged();
            }
        }
        private int _ROLE;
        partial void OnROLEChanging(int value);
        partial void OnROLEChanged();
    }
}
